language: java
jdk:
  - openjdk8
script:
  - mvn clean install -DskipTests=true
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "lihongjie0209"
  - git config --local user.email "lihongjie0209@gmail.com"

deploy:
  provider: releases
  api_key: "940b3211502a868d98166c4afc94c592aa347615"
  file: ./target/cli-demo-1.0-SNAPSHOT.jar
  skip_cleanup: true